### ISSUE TITLE
Add v 2.1.6.0 pls?

### ISSUE THREAD

**Issue by p1nkyy** [kluyg/calibre-kfx-input#1]
Hi can pls add v 2.1.6.0? Thank you!

**Comment by kluyg** [comment]
Sure! Updated to the latest version (2.17.0).

**Comment by p1nkyy** [comment]
> Sure! Updated to the latest version (2.17.0).

Hi, I need 2.16.0 specifically though because 2.17.0 froze on me.
Also how to install? Because when I cloned the github it said plugin has no top level init.py. Apologies for the noob questions. Thanks!

**Comment by kluyg** [comment]
Ah, got it, sorry, I don't have 2.16.0 source code. You can try asking Howell (the author) in https://www.mobileread.com/forums/showthread.php?t=291290

Looks like you're the only one having issues with the new version. Try updating or re-installing Calibre and then install the plugin manually (copy-pasted instructions from https://www.mobileread.com/forums/showthread.php?t=118680):

**To install a plugin using the Calibre GUI:**

1. Download the plugin zip file (https://www.mobileread.com/forums/attachment.php?attachmentid=211919&d=1731067468 from https://www.mobileread.com/forums/showthread.php?t=291290), taking care that it is not unzipped or touched by any antivirus or download managers you use.
2. In Calibre choose **Preferences->Plugins**. Click the **Load plugin from file** button to browse to your plugin .zip file and click OK.
3. You may then be asked which toolbars/menus you would like the plugin to appear on if it is designed to have a user interface. Take care to put it on all you require, remember that there are different toolbars and menus for while your device is connected. You can always change your mind later using **Preferences->Toolbar** to change your selections.
4. **Restart Calibre after installing a plugin**. Ctrl+R is a convenient shortcut for this.
5. As discussed above, your plugin may need further customization using **Customize plugin** from **Preferences->Plugins** or the Plugin Updater dialog.

**Comment by p1nkyy** [comment]
Ah no problem, thanks so much. Initially the newest version causes my Calibre to slow down and crashed. I thought it's because of that, turned out it's because the book I'm trying to convert was too big. In the end I managed to make it work after asking jhowell. You've been very kind & helpful. Thanks a lot!
